### ISSUE TITLE
Fix ansible scripts to include variables defined outside roles

### ISSUE THREAD

**Issue by reg1reg1** [vital2/ansible#12]
Currently, the ansible playbook when running the scripts for the role "computer networks" fails as it is unable to read **frr variable** the global_vars file inside the inventory (which fails even when included under the "all" syntax.

The fix which has been only applied to host "R1"  and has worked and needs to be applied to other hosts. The fix involved creating a **vars** directory which gets properly included as defined in the ansible documentation concerning roles. 
[Link here:](https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#role-default-variables)

**Comment by treddington** [comment]
Explain more Monday

**Comment by reg1reg1** [comment]
As per our discussion, I will remove the file and add the variable over the role script itself.

**Comment by treddington** [comment]
Thanks. After installing for (make. make install) we don’t need the source any longer. I think you can deee it.

**Comment by reg1reg1** [comment]
The changes have been made to fix the variable structure. The script works now as tested on R-1.

**Comment by treddington** [comment]
Excellent
