### ISSUE TITLE
Upgrade VM's in Computer Networks Course

### ISSUE THREAD

**Issue by reg1reg1** [vital2/ansible#22]
## Functional Requirements
- The computer network vm's which are routers namely R1,R2,R3,R4 have FRR installations version **5.0/stable** and these need to be upgraded to **stable/7.1**. This will require a change in the ansible scripts of the respective VM's where the version number is mentioned for the FRR.
- There needs to be a modification to the Iptables in R1. The masquerade rules need to be added to R1 as mentioned in documentation. It will involve addition in the ansible script file as well. The ansible shell module commands need to be added which reflect the below. 
![image](https://user-images.githubusercontent.com/8259506/62413051-cc7fc600-b5d8-11e9-8a8b-6aba7b6df0f2.png)
- Make the iptables persistent

## Technical Requirements
- Start up the VM's with the conf files referring to the backing image.
- Upgrade the ansible script of FRR. The code change branch is __reg1reg1-22-frr-upgrade__
- Modify the file **frr-insall.yml** for each of the router machines to reflect the version change. Git repo for the new FRR is this
[ Frr/stable/7.1 ](https://github.com/FRRouting/frr/tree/stable/7.1)
- As per the new build requirement for FRR, libyang must have dependencies satisfied and its source must be built before the frr. A new ansible task file will be created for monitoring and fixing this.

**Comment by reg1reg1** [comment]
The functional requirements have been documented, awaiting approval by @treddington @deusalexmachina

**Comment by deusalexmachina** [comment]
for masqerade, may also want to add following lines to _/etc/rc.local_ 
```

# load iptables rules from file
iptables-restore < /etc/iptables.conf
```

**Comment by reg1reg1** [comment]
Yes , good point, to make them persistent.

**Comment by reg1reg1** [comment]
Branch-created: reg1reg1-22-frr-upgrade for development.

**Comment by reg1reg1** [comment]
There is noo rc.local on Ubuntu machines, have to create and make the file executable first. Might have to find a work around in Ubuntu to make the iptables persistent.

**Comment by reg1reg1** [comment]
## Update: Libyang Build needs to be configured

Currently writing a new task file to accommodate this. Managed to remove the build errors, now writing the ansible task file.

**Comment by reg1reg1** [comment]
# Update: rc.local is no longer enabled on default Ubuntu18.10, switched to persistent Iptables.

Please review this pull request.
#23

**Comment by reg1reg1** [comment]
Working on local machine when run from ansible 
![image](https://user-images.githubusercontent.com/8259506/62578232-9eb3af00-b86e-11e9-8feb-eee8a7113274.png)
![image](https://user-images.githubusercontent.com/8259506/62578275-b854f680-b86e-11e9-8240-823e8753c7ab.png)
Iptables persist on reboot, iptables-persistent package added in R1's package.yml

**Comment by reg1reg1** [comment]
Updated the desktop client to lxde manually

**Comment by reg1reg1** [comment]
**This has been resolved and implemented. CN course on production is ready for use with latest FRR 7.1, firewall rules to R1. The VM's use a light desktop client lxde (except Kali which still uses GNOME).**
